In [ ]:
#7
import numpy as np
array = np.arange(12)
reshaped_array = array.reshape(2, 3, 2)
print("Reshaped Array:")
print(reshaped_array)

Reshaped Array:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
#8
import numpy as np
array = np.linspace(0, 20, 6)  
print("Array:", array)


Array: [ 0.  4.  8. 12. 16. 20.]


In [ ]:
#9
deep_copy_array = array.copy()
print("Deep Copy:", deep_copy_array)

Deep Copy: [ 0.  4.  8. 12. 16. 20.]


In [ ]:
#10
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((array1, array2, array3), axis=0)
print("newArray:")
print(newArray)


newArray:
[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
#11
sortedArray = np.sort(newArray, axis=None)  # Sorting in a flat manner
print("sortedArray:", sortedArray)

sortedArray: [ 2  4  5  6  7 11 11 12 13 16 25 81]


In [2]:
#12
import numpy as np
newArray = np.array([
    [25, 16],
    [11, 2],
    [13, 4],
    [7, 81],
    [5, 6],
    [11, 12]
])

reshapedArray = newArray[:8].reshape(6, 2)
var1, var2, var3, var4, var5, var6 = reshapedArray
print("Variable 1:", var1)


Variable 1: [25 16]


In [7]:
# 12 
import numpy as np

newArray = np.arange(8)  # Creates an array [0, 1, 2, ..., 7]

reshapedArray = newArray.reshape(4, 2)

var1, var2, var3, var4 = reshapedArray


In [ ]:
#13
one = [10, 11, 12, 13, 14, 15, 16, 17]
two = [20, 21, 22, 23, 24, 25, 26, 27]
three = [0, 1, 2, 3, 4, 5, 6, 7]
comboArray = sorted(one + two + three)
print("comboArray:", comboArray)


comboArray: [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]


In [ ]:
#14
comboArray = [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]

sec1 = comboArray[1]
sec2 = comboArray[2:] 
sec3 = comboArray[3:14]  
sec4 = comboArray[-6:]  
sec5 = comboArray[-len(comboArray):-len(comboArray)+16]  
sec6 = comboArray[20::2]  
sec7 = comboArray[::-5]  

print("sec1 - 2nd element:", sec1)
print("sec2 - 3rd element to last:", sec2)
print("sec3 - 4th to 14th elements:", sec3)
print("sec4 - Last 6 elements:", sec4)
print("sec5 - #0 up to and including #15 (negative index):", sec5)
print("sec6 - From #20 every even element to the end:", sec6)
print("sec7 - From last element moving forward, every 5th element:", sec7)


sec1 - 2nd element: 1
sec2 - 3rd element to last: [2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]
sec3 - 4th to 14th elements: [3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]
sec4 - Last 6 elements: [22, 23, 24, 25, 26, 27]
sec5 - #0 up to and including #15 (negative index): [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17]
sec6 - From #20 every even element to the end: [24, 26]
sec7 - From last element moving forward, every 5th element: [27, 22, 15, 10, 3]


In [ ]:
#15
import pandas as pd
ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"])
quantity = pd.Series([4, 1, 2, 1])
unit = pd.Series(["cups", "cup", "large", "can"])

dinner_df = pd.DataFrame({"Ingredients": ingredients, "Quantity": quantity, "Unit": unit })
print(dinner_df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [ ]:
#16
import pandas as pd
data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}
studentData = pd.DataFrame(data)
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [ ]:
#17
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Deserts"] = deserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [ ]:
#18
sorted_studentData = studentData.sort_values(by=["Name", "address"])
print(sorted_studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [ ]:
#19
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cows_and_goats.csv", index=True)
print("The DataFrame has been saved as 'cows_and_goats.csv'.")


The DataFrame has been saved as 'cows_and_goats.csv'.


In [ ]:
#20
veggie_data = pd.DataFrame({
    "Vegetables": ["Carrot", "Broccoli", "Spinach"],
    "Quantity": [10, 5, 12],
    "Unit": ["lbs", "lbs", "lbs"]
})
veggie_data.to_csv("vegetable_data.csv", index=False)

print("The DataFrame has been saved as 'vegetable_data.csv'.")

The DataFrame has been saved as 'vegetable_data.csv'.


In [27]:
#20 
veggie_data["Price"] = [2.5, 3.0, 1.5]  # Add a new column 'Price'

veggie_data.to_csv("vegetables_with_price.csv", index=False)
print(veggie_data)


  Vegetables  Quantity Unit  Price
0     Carrot        10  lbs    2.5
1   Broccoli         5  lbs    3.0
2    Spinach        12  lbs    1.5
